[build]
  command = "npm ci && npm run build:netlify"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  # Ensure we're in production mode for Netlify builds
  NODE_ENV = "production"
  # Install all dependencies including optional ones for platform-specific binaries
  NPM_CONFIG_OPTIONAL = "true"
  # Don't skip optional dependencies
  NPM_CONFIG_PRODUCTION = "false"

# Disable the Netlify Gatsby plugin to avoid cache issues
# The plugin is causing issues with msgpackr binary files and @parcel/watcher
# We completely remove the plugin configuration instead of trying to disable it
# because the plugin doesn't accept an "enabled" input parameter

[template.environment]
  GATSBY_SANITY_PROJECT_ID = "Sanity Project ID"
  GATSBY_SANITY_DATASET_ID = "Sanity Dataset ID"  
  GATSBY_SANITY_TOKEN = "Sanity Token"
  # IMPORTANT: Remove GATSBY_SANITY_WATCH_MODE from Netlify dashboard - it's no longer needed!
