[build]
  command = "npm ci && npm run build:netlify"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  # Ensure we're in production mode for Netlify builds
  NODE_ENV = "production"
  # Install all dependencies including optional ones for platform-specific binaries
  NPM_CONFIG_OPTIONAL = "true"
  # Don't skip optional dependencies
  NPM_CONFIG_PRODUCTION = "false"

# Configure the Essential Gatsby plugin properly
# This plugin is required for modern Gatsby sites on Netlify
[[plugins]]
  package = "@netlify/plugin-gatsby"

[template.environment]
  GATSBY_SANITY_PROJECT_ID = "Sanity Project ID"
  GATSBY_SANITY_DATASET_ID = "Sanity Dataset ID"  
  GATSBY_SANITY_TOKEN = "Sanity Token"
  # IMPORTANT: Remove GATSBY_SANITY_WATCH_MODE from Netlify dashboard - it's no longer needed!
